#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v3
# autospec commit: 750e50d
#
Name     : oneDPL
Version  : 2022.3.0.rc1
Release  : 2
URL      : https://github.com/oneapi-src/oneDPL/archive/refs/tags/oneDPL-2022.3.0-rc1.tar.gz
Source0  : https://github.com/oneapi-src/oneDPL/archive/refs/tags/oneDPL-2022.3.0-rc1.tar.gz
Summary  : Intel(R) DPC++ Library.
Group    : Development/Tools
License  : Apache-2.0
Requires: oneDPL-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : tbb-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-Ensure-test-binaries-are-built.patch
Patch2: backport-Fix-installation-path-for-generated-cmakefiles.patch

%description
![](https://spec.oneapi.io/oneapi-logo-white-scaled.jpg)
oneDPL is part of [oneAPI](https://oneapi.io)
# oneAPI DPC++ Library (oneDPL)

%package dev
Summary: dev components for the oneDPL package.
Group: Development
Provides: oneDPL-devel = %{version}-%{release}
Requires: oneDPL = %{version}-%{release}

%description dev
dev components for the oneDPL package.


%package doc
Summary: doc components for the oneDPL package.
Group: Documentation

%description doc
doc components for the oneDPL package.


%package license
Summary: license components for the oneDPL package.
Group: Default

%description license
license components for the oneDPL package.


%prep
%setup -q -n oneDPL-oneDPL-2022.3.0-rc1
cd %{_builddir}/oneDPL-oneDPL-2022.3.0-rc1
%patch -P 1 -p1
%patch -P 2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707091646
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test
cd ../clr-build-avx2;
make test || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707091646
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oneDPL
cp %{_builddir}/oneDPL-oneDPL-2022.3.0-rc1/licensing/LICENSE.txt %{buildroot}/usr/share/package-licenses/oneDPL/76cdb6c64722fbcd432e868ee1498e304e967204 || :
pushd clr-build-avx2
%make_install_v3  || :
popd
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/oneapi/dpl/algorithm
/usr/include/oneapi/dpl/array
/usr/include/oneapi/dpl/async
/usr/include/oneapi/dpl/cmath
/usr/include/oneapi/dpl/complex
/usr/include/oneapi/dpl/cstddef
/usr/include/oneapi/dpl/cstring
/usr/include/oneapi/dpl/dynamic_selection
/usr/include/oneapi/dpl/execution
/usr/include/oneapi/dpl/functional
/usr/include/oneapi/dpl/internal/async_extension_defs.h
/usr/include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
/usr/include/oneapi/dpl/internal/async_impl/glue_async_impl.h
/usr/include/oneapi/dpl/internal/binary_search_extension_defs.h
/usr/include/oneapi/dpl/internal/binary_search_impl.h
/usr/include/oneapi/dpl/internal/by_segment_extension_defs.h
/usr/include/oneapi/dpl/internal/common_config.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/policy_traits.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/scoring_policy_defs.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
/usr/include/oneapi/dpl/internal/dynamic_selection_traits.h
/usr/include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
/usr/include/oneapi/dpl/internal/function.h
/usr/include/oneapi/dpl/internal/gcd_impl.h
/usr/include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
/usr/include/oneapi/dpl/internal/iterator_impl.h
/usr/include/oneapi/dpl/internal/random_impl/bernoulli_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/cauchy_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/discard_block_engine.h
/usr/include/oneapi/dpl/internal/random_impl/exponential_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/extreme_value_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/geometric_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h
/usr/include/oneapi/dpl/internal/random_impl/lognormal_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/normal_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/random_common.h
/usr/include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h
/usr/include/oneapi/dpl/internal/random_impl/uniform_int_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/weibull_distribution.h
/usr/include/oneapi/dpl/internal/reduce_by_segment_impl.h
/usr/include/oneapi/dpl/internal/scan_by_segment_impl.h
/usr/include/oneapi/dpl/internal/serial_algorithm_impl.h
/usr/include/oneapi/dpl/internal/serial_numeric_impl.h
/usr/include/oneapi/dpl/iterator
/usr/include/oneapi/dpl/limits
/usr/include/oneapi/dpl/memory
/usr/include/oneapi/dpl/numeric
/usr/include/oneapi/dpl/optional
/usr/include/oneapi/dpl/pstl/algorithm_fwd.h
/usr/include/oneapi/dpl/pstl/algorithm_impl.h
/usr/include/oneapi/dpl/pstl/execution_defs.h
/usr/include/oneapi/dpl/pstl/execution_impl.h
/usr/include/oneapi/dpl/pstl/experimental/algorithm
/usr/include/oneapi/dpl/pstl/experimental/internal/for_loop.h
/usr/include/oneapi/dpl/pstl/experimental/internal/for_loop_impl.h
/usr/include/oneapi/dpl/pstl/experimental/internal/induction.h
/usr/include/oneapi/dpl/pstl/experimental/internal/induction_impl.h
/usr/include/oneapi/dpl/pstl/experimental/internal/reduction.h
/usr/include/oneapi/dpl/pstl/experimental/internal/reduction_impl.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_defs.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_impl.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
/usr/include/oneapi/dpl/pstl/glue_execution_defs.h
/usr/include/oneapi/dpl/pstl/glue_memory_defs.h
/usr/include/oneapi/dpl/pstl/glue_memory_impl.h
/usr/include/oneapi/dpl/pstl/glue_numeric_defs.h
/usr/include/oneapi/dpl/pstl/glue_numeric_impl.h
/usr/include/oneapi/dpl/pstl/glue_numeric_ranges_defs.h
/usr/include/oneapi/dpl/pstl/glue_numeric_ranges_impl.h
/usr/include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
/usr/include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/utils_hetero.h
/usr/include/oneapi/dpl/pstl/iterator_defs.h
/usr/include/oneapi/dpl/pstl/iterator_impl.h
/usr/include/oneapi/dpl/pstl/memory_fwd.h
/usr/include/oneapi/dpl/pstl/memory_impl.h
/usr/include/oneapi/dpl/pstl/numeric_fwd.h
/usr/include/oneapi/dpl/pstl/numeric_impl.h
/usr/include/oneapi/dpl/pstl/omp/parallel_for.h
/usr/include/oneapi/dpl/pstl/omp/parallel_for_each.h
/usr/include/oneapi/dpl/pstl/omp/parallel_invoke.h
/usr/include/oneapi/dpl/pstl/omp/parallel_merge.h
/usr/include/oneapi/dpl/pstl/omp/parallel_reduce.h
/usr/include/oneapi/dpl/pstl/omp/parallel_scan.h
/usr/include/oneapi/dpl/pstl/omp/parallel_stable_partial_sort.h
/usr/include/oneapi/dpl/pstl/omp/parallel_stable_sort.h
/usr/include/oneapi/dpl/pstl/omp/parallel_transform_reduce.h
/usr/include/oneapi/dpl/pstl/omp/parallel_transform_scan.h
/usr/include/oneapi/dpl/pstl/omp/util.h
/usr/include/oneapi/dpl/pstl/onedpl_config.h
/usr/include/oneapi/dpl/pstl/parallel_backend.h
/usr/include/oneapi/dpl/pstl/parallel_backend_omp.h
/usr/include/oneapi/dpl/pstl/parallel_backend_serial.h
/usr/include/oneapi/dpl/pstl/parallel_backend_tbb.h
/usr/include/oneapi/dpl/pstl/parallel_backend_utils.h
/usr/include/oneapi/dpl/pstl/parallel_impl.h
/usr/include/oneapi/dpl/pstl/pstl_config.h
/usr/include/oneapi/dpl/pstl/ranges/nanorange.hpp
/usr/include/oneapi/dpl/pstl/ranges/nanorange_ext.h
/usr/include/oneapi/dpl/pstl/ranges_defs.h
/usr/include/oneapi/dpl/pstl/tuple_impl.h
/usr/include/oneapi/dpl/pstl/unseq_backend_simd.h
/usr/include/oneapi/dpl/pstl/utils.h
/usr/include/oneapi/dpl/pstl/utils_ranges.h
/usr/include/oneapi/dpl/random
/usr/include/oneapi/dpl/ranges
/usr/include/oneapi/dpl/ratio
/usr/include/oneapi/dpl/tuple
/usr/include/oneapi/dpl/type_traits
/usr/include/oneapi/dpl/utility
/usr/include/pstl_offload/algorithm
/usr/include/pstl_offload/any
/usr/include/pstl_offload/array
/usr/include/pstl_offload/atomic
/usr/include/pstl_offload/barrier
/usr/include/pstl_offload/bit
/usr/include/pstl_offload/bitset
/usr/include/pstl_offload/cassert
/usr/include/pstl_offload/cctype
/usr/include/pstl_offload/cerrno
/usr/include/pstl_offload/cfenv
/usr/include/pstl_offload/cfloat
/usr/include/pstl_offload/charconv
/usr/include/pstl_offload/chrono
/usr/include/pstl_offload/cinttypes
/usr/include/pstl_offload/climits
/usr/include/pstl_offload/clocale
/usr/include/pstl_offload/cmath
/usr/include/pstl_offload/codecvt
/usr/include/pstl_offload/compare
/usr/include/pstl_offload/complex
/usr/include/pstl_offload/concepts
/usr/include/pstl_offload/condition_variable
/usr/include/pstl_offload/coroutine
/usr/include/pstl_offload/csetjmp
/usr/include/pstl_offload/csignal
/usr/include/pstl_offload/cstdarg
/usr/include/pstl_offload/cstddef
/usr/include/pstl_offload/cstdint
/usr/include/pstl_offload/cstdio
/usr/include/pstl_offload/cstdlib
/usr/include/pstl_offload/cstring
/usr/include/pstl_offload/ctime
/usr/include/pstl_offload/cuchar
/usr/include/pstl_offload/cwchar
/usr/include/pstl_offload/cwctype
/usr/include/pstl_offload/deque
/usr/include/pstl_offload/exception
/usr/include/pstl_offload/execution
/usr/include/pstl_offload/filesystem
/usr/include/pstl_offload/format
/usr/include/pstl_offload/forward_list
/usr/include/pstl_offload/fstream
/usr/include/pstl_offload/functional
/usr/include/pstl_offload/future
/usr/include/pstl_offload/initializer_list
/usr/include/pstl_offload/internal/algorithm_redirection_impl.h
/usr/include/pstl_offload/internal/memory_redirection_impl.h
/usr/include/pstl_offload/internal/numeric_redirection_impl.h
/usr/include/pstl_offload/internal/usm_memory_replacement.h
/usr/include/pstl_offload/internal/usm_memory_replacement_common.h
/usr/include/pstl_offload/iomanip
/usr/include/pstl_offload/ios
/usr/include/pstl_offload/iosfwd
/usr/include/pstl_offload/iostream
/usr/include/pstl_offload/istream
/usr/include/pstl_offload/iterator
/usr/include/pstl_offload/latch
/usr/include/pstl_offload/limits
/usr/include/pstl_offload/list
/usr/include/pstl_offload/locale
/usr/include/pstl_offload/map
/usr/include/pstl_offload/memory
/usr/include/pstl_offload/memory_resource
/usr/include/pstl_offload/mutex
/usr/include/pstl_offload/new
/usr/include/pstl_offload/numbers
/usr/include/pstl_offload/numeric
/usr/include/pstl_offload/oneapi/dpl/algorithm
/usr/include/pstl_offload/oneapi/dpl/array
/usr/include/pstl_offload/oneapi/dpl/async
/usr/include/pstl_offload/oneapi/dpl/cmath
/usr/include/pstl_offload/oneapi/dpl/complex
/usr/include/pstl_offload/oneapi/dpl/cstddef
/usr/include/pstl_offload/oneapi/dpl/cstring
/usr/include/pstl_offload/oneapi/dpl/dynamic_selection
/usr/include/pstl_offload/oneapi/dpl/execution
/usr/include/pstl_offload/oneapi/dpl/functional
/usr/include/pstl_offload/oneapi/dpl/iterator
/usr/include/pstl_offload/oneapi/dpl/limits
/usr/include/pstl_offload/oneapi/dpl/memory
/usr/include/pstl_offload/oneapi/dpl/numeric
/usr/include/pstl_offload/oneapi/dpl/optional
/usr/include/pstl_offload/oneapi/dpl/random
/usr/include/pstl_offload/oneapi/dpl/ranges
/usr/include/pstl_offload/oneapi/dpl/ratio
/usr/include/pstl_offload/oneapi/dpl/tuple
/usr/include/pstl_offload/oneapi/dpl/type_traits
/usr/include/pstl_offload/oneapi/dpl/utility
/usr/include/pstl_offload/oneapi/tbb/blocked_range.h
/usr/include/pstl_offload/oneapi/tbb/blocked_range2d.h
/usr/include/pstl_offload/oneapi/tbb/blocked_range3d.h
/usr/include/pstl_offload/oneapi/tbb/blocked_rangeNd.h
/usr/include/pstl_offload/oneapi/tbb/cache_aligned_allocator.h
/usr/include/pstl_offload/oneapi/tbb/collaborative_call_once.h
/usr/include/pstl_offload/oneapi/tbb/combinable.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_hash_map.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_lru_cache.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_map.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_priority_queue.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_queue.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_set.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_unordered_map.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_unordered_set.h
/usr/include/pstl_offload/oneapi/tbb/concurrent_vector.h
/usr/include/pstl_offload/oneapi/tbb/enumerable_thread_specific.h
/usr/include/pstl_offload/oneapi/tbb/flow_graph.h
/usr/include/pstl_offload/oneapi/tbb/flow_graph_abstractions.h
/usr/include/pstl_offload/oneapi/tbb/global_control.h
/usr/include/pstl_offload/oneapi/tbb/info.h
/usr/include/pstl_offload/oneapi/tbb/memory_pool.h
/usr/include/pstl_offload/oneapi/tbb/mutex.h
/usr/include/pstl_offload/oneapi/tbb/null_mutex.h
/usr/include/pstl_offload/oneapi/tbb/null_rw_mutex.h
/usr/include/pstl_offload/oneapi/tbb/parallel_for.h
/usr/include/pstl_offload/oneapi/tbb/parallel_for_each.h
/usr/include/pstl_offload/oneapi/tbb/parallel_invoke.h
/usr/include/pstl_offload/oneapi/tbb/parallel_pipeline.h
/usr/include/pstl_offload/oneapi/tbb/parallel_reduce.h
/usr/include/pstl_offload/oneapi/tbb/parallel_scan.h
/usr/include/pstl_offload/oneapi/tbb/parallel_sort.h
/usr/include/pstl_offload/oneapi/tbb/partitioner.h
/usr/include/pstl_offload/oneapi/tbb/profiling.h
/usr/include/pstl_offload/oneapi/tbb/queuing_mutex.h
/usr/include/pstl_offload/oneapi/tbb/queuing_rw_mutex.h
/usr/include/pstl_offload/oneapi/tbb/rw_mutex.h
/usr/include/pstl_offload/oneapi/tbb/scalable_allocator.h
/usr/include/pstl_offload/oneapi/tbb/spin_mutex.h
/usr/include/pstl_offload/oneapi/tbb/spin_rw_mutex.h
/usr/include/pstl_offload/oneapi/tbb/task.h
/usr/include/pstl_offload/oneapi/tbb/task_arena.h
/usr/include/pstl_offload/oneapi/tbb/task_group.h
/usr/include/pstl_offload/oneapi/tbb/task_scheduler_observer.h
/usr/include/pstl_offload/oneapi/tbb/tbb_allocator.h
/usr/include/pstl_offload/oneapi/tbb/tbbmalloc_proxy.h
/usr/include/pstl_offload/oneapi/tbb/tick_count.h
/usr/include/pstl_offload/oneapi/tbb/version.h
/usr/include/pstl_offload/optional
/usr/include/pstl_offload/ostream
/usr/include/pstl_offload/queue
/usr/include/pstl_offload/random
/usr/include/pstl_offload/ranges
/usr/include/pstl_offload/ratio
/usr/include/pstl_offload/regex
/usr/include/pstl_offload/scoped_allocator
/usr/include/pstl_offload/semaphore
/usr/include/pstl_offload/set
/usr/include/pstl_offload/shared_mutex
/usr/include/pstl_offload/source_location
/usr/include/pstl_offload/span
/usr/include/pstl_offload/sstream
/usr/include/pstl_offload/stack
/usr/include/pstl_offload/stdexcept
/usr/include/pstl_offload/stdlib.h
/usr/include/pstl_offload/stop_token
/usr/include/pstl_offload/streambuf
/usr/include/pstl_offload/string
/usr/include/pstl_offload/string_view
/usr/include/pstl_offload/strstream
/usr/include/pstl_offload/sycl/sycl.hpp
/usr/include/pstl_offload/syncstream
/usr/include/pstl_offload/system_error
/usr/include/pstl_offload/thread
/usr/include/pstl_offload/tuple
/usr/include/pstl_offload/type_traits
/usr/include/pstl_offload/typeindex
/usr/include/pstl_offload/typeinfo
/usr/include/pstl_offload/unordered_map
/usr/include/pstl_offload/unordered_set
/usr/include/pstl_offload/utility
/usr/include/pstl_offload/valarray
/usr/include/pstl_offload/variant
/usr/include/pstl_offload/vector
/usr/include/pstl_offload/version
/usr/lib64/cmake/oneDPL/dpl.pc
/usr/lib64/cmake/oneDPL/oneDPLConfig.cmake
/usr/lib64/cmake/oneDPL/oneDPLConfigVersion.cmake
/usr/lib64/cmake/oneDPL/oneDPLWindowsIntelLLVMApply.cmake
/usr/lib64/cmake/oneDPL/oneDPLWindowsIntelLLVMConfig.cmake

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/oneDPL/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oneDPL/76cdb6c64722fbcd432e868ee1498e304e967204
