#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : oneDPL
Version  : 2022.7.1
Release  : 3
URL      : https://github.com/uxlfoundation/oneDPL/archive/refs/tags/oneDPL-2022.7.1-release.tar.gz
Source0  : https://github.com/uxlfoundation/oneDPL/archive/refs/tags/oneDPL-2022.7.1-release.tar.gz
Summary  : Intel(R) DPC++ Library.
Group    : Development/Tools
License  : Apache-2.0
Requires: oneDPL-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : tbb-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: backport-Ensure-test-binaries-are-built.patch
Patch2: backport-Fix-installation-path-for-generated-cmakefiles.patch

%description
# oneAPI DPC++ Library (oneDPL) <img align="right" width="200" height="100" src=https://github.com/uxlfoundation/artwork/blob/main/foundation/uxl-foundation-logo-horizontal-color.svg>
[![Apache License Version 2.0](https://img.shields.io/badge/license-Apache_2.0-green.svg)](LICENSE.txt) [![oneDPL CI](https://github.com/oneapi-src/oneDPL/actions/workflows/ci.yml/badge.svg)](https://github.com/oneapi-src/oneDPL/actions/workflows/ci.yml?query=branch%3Amaster)
[![Join the community on GitHub Discussions](https://badgen.net/badge/join%20the%20discussion/on%20github/blue?icon=github)](https://github.com/oneapi-src/oneDPL/discussions)
[![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/oneapi-src/oneDPL/badge)](https://securityscorecards.dev/viewer/?uri=github.com/oneapi-src/oneDPL)

%package dev
Summary: dev components for the oneDPL package.
Group: Development
Provides: oneDPL-devel = %{version}-%{release}
Requires: oneDPL = %{version}-%{release}

%description dev
dev components for the oneDPL package.


%package doc
Summary: doc components for the oneDPL package.
Group: Documentation

%description doc
doc components for the oneDPL package.


%package license
Summary: license components for the oneDPL package.
Group: Default

%description license
license components for the oneDPL package.


%prep
%setup -q -n oneDPL-oneDPL-2022.7.1-release
cd %{_builddir}/oneDPL-oneDPL-2022.7.1-release
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a oneDPL-oneDPL-2022.7.1-release buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737737384
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test
cd ../../buildavx2/clr-build-avx2;
make test || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1737737384
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oneDPL
cp %{_builddir}/oneDPL-oneDPL-%{version}-release/LICENSE.txt %{buildroot}/usr/share/package-licenses/oneDPL/76cdb6c64722fbcd432e868ee1498e304e967204 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/oneapi/dpl/algorithm
/usr/include/oneapi/dpl/array
/usr/include/oneapi/dpl/async
/usr/include/oneapi/dpl/cmath
/usr/include/oneapi/dpl/complex
/usr/include/oneapi/dpl/cstddef
/usr/include/oneapi/dpl/cstring
/usr/include/oneapi/dpl/dynamic_selection
/usr/include/oneapi/dpl/execution
/usr/include/oneapi/dpl/experimental/kernel_templates
/usr/include/oneapi/dpl/experimental/kt/esimd_radix_sort.h
/usr/include/oneapi/dpl/experimental/kt/internal/esimd_defs.h
/usr/include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_dispatchers.h
/usr/include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_kernels.h
/usr/include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_submitters.h
/usr/include/oneapi/dpl/experimental/kt/internal/esimd_radix_sort_utils.h
/usr/include/oneapi/dpl/experimental/kt/kernel_param.h
/usr/include/oneapi/dpl/experimental/kt/single_pass_scan.h
/usr/include/oneapi/dpl/functional
/usr/include/oneapi/dpl/internal/async_extension_defs.h
/usr/include/oneapi/dpl/internal/async_impl/async_impl_hetero.h
/usr/include/oneapi/dpl/internal/async_impl/glue_async_impl.h
/usr/include/oneapi/dpl/internal/binary_search_extension_defs.h
/usr/include/oneapi/dpl/internal/binary_search_impl.h
/usr/include/oneapi/dpl/internal/by_segment_extension_defs.h
/usr/include/oneapi/dpl/internal/common_config.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/auto_tune_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/backend_traits.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/dynamic_load_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/fixed_resource_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/policy_traits.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/round_robin_policy.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/scoring_policy_defs.h
/usr/include/oneapi/dpl/internal/dynamic_selection_impl/sycl_backend.h
/usr/include/oneapi/dpl/internal/dynamic_selection_traits.h
/usr/include/oneapi/dpl/internal/exclusive_scan_by_segment_impl.h
/usr/include/oneapi/dpl/internal/function.h
/usr/include/oneapi/dpl/internal/gcd_impl.h
/usr/include/oneapi/dpl/internal/inclusive_scan_by_segment_impl.h
/usr/include/oneapi/dpl/internal/iterator_impl.h
/usr/include/oneapi/dpl/internal/random_impl/bernoulli_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/cauchy_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/discard_block_engine.h
/usr/include/oneapi/dpl/internal/random_impl/exponential_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/extreme_value_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/geometric_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/linear_congruential_engine.h
/usr/include/oneapi/dpl/internal/random_impl/lognormal_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/normal_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/philox_engine.h
/usr/include/oneapi/dpl/internal/random_impl/random_common.h
/usr/include/oneapi/dpl/internal/random_impl/subtract_with_carry_engine.h
/usr/include/oneapi/dpl/internal/random_impl/uniform_int_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/uniform_real_distribution.h
/usr/include/oneapi/dpl/internal/random_impl/weibull_distribution.h
/usr/include/oneapi/dpl/internal/reduce_by_segment_impl.h
/usr/include/oneapi/dpl/internal/scan_by_segment_impl.h
/usr/include/oneapi/dpl/internal/serial_algorithm_impl.h
/usr/include/oneapi/dpl/internal/serial_numeric_impl.h
/usr/include/oneapi/dpl/internal/version_impl.h
/usr/include/oneapi/dpl/iterator
/usr/include/oneapi/dpl/limits
/usr/include/oneapi/dpl/memory
/usr/include/oneapi/dpl/numeric
/usr/include/oneapi/dpl/optional
/usr/include/oneapi/dpl/pstl/algorithm_fwd.h
/usr/include/oneapi/dpl/pstl/algorithm_impl.h
/usr/include/oneapi/dpl/pstl/algorithm_ranges_impl.h
/usr/include/oneapi/dpl/pstl/execution_defs.h
/usr/include/oneapi/dpl/pstl/execution_impl.h
/usr/include/oneapi/dpl/pstl/experimental/algorithm
/usr/include/oneapi/dpl/pstl/experimental/internal/for_loop.h
/usr/include/oneapi/dpl/pstl/experimental/internal/for_loop_impl.h
/usr/include/oneapi/dpl/pstl/experimental/internal/induction.h
/usr/include/oneapi/dpl/pstl/experimental/internal/induction_impl.h
/usr/include/oneapi/dpl/pstl/experimental/internal/reduction.h
/usr/include/oneapi/dpl/pstl/experimental/internal/reduction_impl.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_defs.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_impl.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_ranges_defs.h
/usr/include/oneapi/dpl/pstl/glue_algorithm_ranges_impl.h
/usr/include/oneapi/dpl/pstl/glue_execution_defs.h
/usr/include/oneapi/dpl/pstl/glue_memory_defs.h
/usr/include/oneapi/dpl/pstl/glue_memory_impl.h
/usr/include/oneapi/dpl/pstl/glue_numeric_defs.h
/usr/include/oneapi/dpl/pstl/glue_numeric_impl.h
/usr/include/oneapi/dpl/pstl/glue_numeric_ranges_defs.h
/usr/include/oneapi/dpl/pstl/glue_numeric_ranges_impl.h
/usr/include/oneapi/dpl/pstl/hetero/algorithm_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/algorithm_ranges_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/execution_sycl_defs.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_fpga.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_histogram.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_merge_sort.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_radix_sort_one_wg.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_reduce_then_scan.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/parallel_backend_sycl_utils.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/sycl_defs.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/sycl_iterator.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/sycl_traits.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/unseq_backend_sycl.h
/usr/include/oneapi/dpl/pstl/hetero/dpcpp/utils_ranges_sycl.h
/usr/include/oneapi/dpl/pstl/hetero/histogram_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/numeric_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/numeric_ranges_impl_hetero.h
/usr/include/oneapi/dpl/pstl/hetero/utils_hetero.h
/usr/include/oneapi/dpl/pstl/histogram_binhash_utils.h
/usr/include/oneapi/dpl/pstl/histogram_extension_defs.h
/usr/include/oneapi/dpl/pstl/histogram_impl.h
/usr/include/oneapi/dpl/pstl/iterator_defs.h
/usr/include/oneapi/dpl/pstl/iterator_impl.h
/usr/include/oneapi/dpl/pstl/memory_fwd.h
/usr/include/oneapi/dpl/pstl/memory_impl.h
/usr/include/oneapi/dpl/pstl/numeric_fwd.h
/usr/include/oneapi/dpl/pstl/numeric_impl.h
/usr/include/oneapi/dpl/pstl/omp/parallel_for.h
/usr/include/oneapi/dpl/pstl/omp/parallel_for_each.h
/usr/include/oneapi/dpl/pstl/omp/parallel_invoke.h
/usr/include/oneapi/dpl/pstl/omp/parallel_merge.h
/usr/include/oneapi/dpl/pstl/omp/parallel_reduce.h
/usr/include/oneapi/dpl/pstl/omp/parallel_scan.h
/usr/include/oneapi/dpl/pstl/omp/parallel_stable_partial_sort.h
/usr/include/oneapi/dpl/pstl/omp/parallel_stable_sort.h
/usr/include/oneapi/dpl/pstl/omp/parallel_transform_reduce.h
/usr/include/oneapi/dpl/pstl/omp/parallel_transform_scan.h
/usr/include/oneapi/dpl/pstl/omp/util.h
/usr/include/oneapi/dpl/pstl/onedpl_config.h
/usr/include/oneapi/dpl/pstl/parallel_backend.h
/usr/include/oneapi/dpl/pstl/parallel_backend_omp.h
/usr/include/oneapi/dpl/pstl/parallel_backend_serial.h
/usr/include/oneapi/dpl/pstl/parallel_backend_tbb.h
/usr/include/oneapi/dpl/pstl/parallel_backend_utils.h
/usr/include/oneapi/dpl/pstl/parallel_impl.h
/usr/include/oneapi/dpl/pstl/pstl_config.h
/usr/include/oneapi/dpl/pstl/ranges/nanorange.hpp
/usr/include/oneapi/dpl/pstl/ranges/nanorange_ext.h
/usr/include/oneapi/dpl/pstl/ranges_defs.h
/usr/include/oneapi/dpl/pstl/tuple_impl.h
/usr/include/oneapi/dpl/pstl/unseq_backend_simd.h
/usr/include/oneapi/dpl/pstl/utils.h
/usr/include/oneapi/dpl/pstl/utils_ranges.h
/usr/include/oneapi/dpl/random
/usr/include/oneapi/dpl/ranges
/usr/include/oneapi/dpl/ratio
/usr/include/oneapi/dpl/tuple
/usr/include/oneapi/dpl/type_traits
/usr/include/oneapi/dpl/utility
/usr/include/oneapi/dpl/version
/usr/lib64/cmake/oneDPL/dpl.pc
/usr/lib64/cmake/oneDPL/oneDPLConfig.cmake
/usr/lib64/cmake/oneDPL/oneDPLConfigVersion.cmake
/usr/lib64/cmake/oneDPL/oneDPLWindowsIntelLLVMApply.cmake
/usr/lib64/cmake/oneDPL/oneDPLWindowsIntelLLVMConfig.cmake

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/oneDPL/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oneDPL/76cdb6c64722fbcd432e868ee1498e304e967204
